# Generated by Django 6.0.5 on 2026-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='書名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('summary', models.TextField(verbose_name='內容摘要')),
                ('category', models.CharField(max_length=50, verbose_name='分類')),
                ('reward_points', models.IntegerField(default=0, verbose_name='獎勵點數')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='封面圖片網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
        ),
    ]
