# Generated by Django 6.0.5 on 2026-05-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(max_length=100, verbose_name='讀者名稱')),
                ('progress', models.IntegerField(default=0, verbose_name='閱讀進度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('earned_points', models.IntegerField(default=0, verbose_name='已獲得點數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='myapp.book', verbose_name='對應書籍')),
            ],
        ),
    ]
