# Generated by Django 6.0.5 on 2026-05-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_readingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecord',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='閱讀心得'),
        ),
    ]
